org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=gwoodworks
mod.name=guita's Woodworks
mod.group=com.macuguita
mod.version=1.2.6

deps.fabric-loader=0.18.4
deps.macu_lib=2.0.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=NTFyR6MX
publish.curseforge=1308420
#publish.additionalVersions=
