org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=gwoodworks
mod.name=guita's Woodworks
mod.group=com.macuguita
mod.version=0.1.0

deps.fabric-loader=0.18.4
deps.kaleido=0.3.3+1.3.2
deps.macu_lib=2.0.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=